version: '3.9'

services:
  db:
    build:
      context: ./docker/database
    container_name: symfony_react_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      DATABASE_URL: 'mysql://root:root@db:3306/nodes_app?serverVersion=8&charset=utf8mb4'
    ports:
      - "4306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql

  symfony_react:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    container_name: symfony_react_app
    depends_on:
      - db
    ports:
      - "2520:8080"
    restart: always
    volumes:
      - .:/usr/src/app
    entrypoint: sh /usr/src/app/docker/apache/start_server.sh